export const countriesMock = {
  NO: {
    address1: "Karl Johans gate 12",
    address2: "Apartment 5A",
    city: "Oslo",
    company: "Norsk AS",
    country: "Norway",
    country_code: "NO",
    email: "norwegian.user@example.com",
    first_name: "Ola",
    last_name: "Nordmann",
    phone: "4723456789",
    phone_code: "47",
    province: "",
    province_code: "",
    zip: "0154",
  },
  GB: {
    address1: "123 High Street",
    address2: "Suite 4B",
    city: "London",
    company: "Example Ltd.",
    country: "United Kingdom",
    country_code: "GB",
    email: "john.doe@example.com",
    first_name: "John",
    last_name: "Doe",
    phone: "01234567890",
    phone_code: "44",
    province: "",
    province_code: "",
    zip: "SW1A 1AA",
  },
  DE: {
    address1: "Musterstraße 123",
    address2: "EG",
    city: "Berlin",
    company: "Beispiel GmbH",
    country: "Germany",
    country_code: "DE",
    email: "german.user@example.com",
    first_name: "Hans",
    last_name: "Müller",
    phone: "493012345678",
    phone_code: "49",
    province: "",
    province_code: "",
    zip: "10115",
  },
  NL: {
    address1: "Damrak 1-5",
    address2: "",
    city: "Amsterdam",
    company: "Nederland BV",
    country: "Netherlands",
    country_code: "NL",
    email: "dutch.user@example.com",
    first_name: "Jan",
    last_name: "Jansen",
    phone: "31201234567",
    phone_code: "31",
    province: "",
    province_code: "",
    zip: "1012 JS",
  },
  US: {
    address1: "456 Elm Street",
    address2: "Apt 9",
    city: "New York",
    company: "USA Inc.",
    country: "United States",
    country_code: "US",
    email: "american.user@example.com",
    first_name: "Jane",
    last_name: "Smith",
    phone: "1234567890",
    phone_code: "1",
    province: "New York",
    province_code: "NY",
    zip: "10001",
  },
  CA: {
    address1: "789 Maple Road",
    address2: "",
    city: "Toronto",
    company: "Canada Corp.",
    country: "Canada",
    country_code: "CA",
    email: "canadian.user@example.com",
    first_name: "Emily",
    last_name: "Johnson",
    phone: "14161234567",
    phone_code: "1",
    province: "Ontario",
    province_code: "ON",
    zip: "M5H 2N2",
  },
  AT: {
    address1: "Mariahilfer Straße 99",
    address2: "2. Stock",
    city: "Vienna",
    company: "Österreich GmbH",
    country: "Austria",
    country_code: "AT",
    email: "austrian.user@example.com",
    first_name: "Franz",
    last_name: "Huber",
    phone: "43123456789",
    phone_code: "43",
    province: "",
    province_code: "",
    zip: "1070",
  },
  BE: {
    address1: "Rue de la Loi 200",
    address2: "",
    city: "Brussels",
    company: "Belgique SA",
    country: "Belgium",
    country_code: "BE",
    email: "belgian.user@example.com",
    first_name: "Philippe",
    last_name: "Van Damme",
    phone: "32212345678",
    phone_code: "32",
    province: "",
    province_code: "",
    zip: "1000",
  },
  BG: {
    address1: "Bul. Vitosha 1",
    address2: "Office 7",
    city: "Sofia",
    company: "Bulgaria EOOD",
    country: "Bulgaria",
    country_code: "BG",
    email: "bulgarian.user@example.com",
    first_name: "Ivan",
    last_name: "Ivanov",
    phone: "35921234567",
    phone_code: "359",
    province: "",
    province_code: "",
    zip: "1000",
  },
  HR: {
    address1: "Trg Bana Jelačića 5",
    address2: "",
    city: "Zagreb",
    company: "Hrvatska d.o.o.",
    country: "Croatia",
    country_code: "HR",
    email: "croatian.user@example.com",
    first_name: "Ante",
    last_name: "Horvat",
    phone: "38511234567",
    phone_code: "385",
    province: "",
    province_code: "",
    zip: "10000",
  },
  CY: {
    address1: "Arch. Makarios III Avenue 2",
    address2: "",
    city: "Nicosia",
    company: "Cyprus Ltd.",
    country: "Cyprus",
    country_code: "CY",
    email: "cypriot.user@example.com",
    first_name: "Andreas",
    last_name: "Ioannou",
    phone: "35722123456",
    phone_code: "357",
    province: "",
    province_code: "",
    zip: "1010",
  },
  EE: {
    address1: "Pikk 23",
    address2: "",
    city: "Tallinn",
    company: "Estonia AS",
    country: "Estonia",
    country_code: "EE",
    email: "estonian.user@example.com",
    first_name: "Mati",
    last_name: "Tamm",
    phone: "37251234567",
    phone_code: "372",
    province: "",
    province_code: "",
    zip: "10130",
  },
  FI: {
    address1: "Mannerheimintie 10",
    address2: "",
    city: "Helsinki",
    company: "Suomi Oy",
    country: "Finland",
    country_code: "FI",
    email: "finnish.user@example.com",
    first_name: "Pekka",
    last_name: "Korhonen",
    phone: "358912345678",
    phone_code: "358",
    province: "",
    province_code: "",
    zip: "00100",
  },
  FR: {
    address1: "10 Avenue des Champs-Élysées",
    address2: "",
    city: "Paris",
    company: "France SARL",
    country: "France",
    country_code: "FR",
    email: "french.user@example.com",
    first_name: "Jean",
    last_name: "Dupont",
    phone: "33123456789",
    phone_code: "33",
    province: "",
    province_code: "",
    zip: "75008",
  },
  GR: {
    address1: "3 Ermou Street",
    address2: "",
    city: "Athens",
    company: "Greece AE",
    country: "Greece",
    country_code: "GR",
    email: "greek.user@example.com",
    first_name: "Nikos",
    last_name: "Papadopoulos",
    phone: "30211234567",
    phone_code: "30",
    province: "",
    province_code: "",
    zip: "10563",
  },
  IE: {
    address1: "1 Grafton Street",
    address2: "",
    city: "Dublin",
    company: "Ireland Ltd.",
    country: "Ireland",
    country_code: "IE",
    email: "irish.user@example.com",
    first_name: "Patrick",
    last_name: "O'Brien",
    phone: "35312345678",
    phone_code: "353",
    province: "",
    province_code: "",
    zip: "D02 HT44",
  },
  IT: {
    address1: "Via Roma 10",
    address2: "",
    city: "Rome",
    company: "Italia SRL",
    country: "Italy",
    country_code: "IT",
    email: "italian.user@example.com",
    first_name: "Giovanni",
    last_name: "Rossi",
    phone: "390612345678",
    phone_code: "39",
    province: "",
    province_code: "",
    zip: "00185",
  },
  LV: {
    address1: "Brīvības iela 10",
    address2: "",
    city: "Riga",
    company: "Latvia SIA",
    country: "Latvia",
    country_code: "LV",
    email: "latvian.user@example.com",
    first_name: "Janis",
    last_name: "Berzins",
    phone: "37121234567",
    phone_code: "371",
    province: "",
    province_code: "",
    zip: "LV-1010",
  },
  LT: {
    address1: "Gedimino pr. 5",
    address2: "",
    city: "Vilnius",
    company: "Lithuania UAB",
    country: "Lithuania",
    country_code: "LT",
    email: "lithuanian.user@example.com",
    first_name: "Andrius",
    last_name: "Petrauskas",
    phone: "37061234567",
    phone_code: "370",
    province: "",
    province_code: "",
    zip: "LT-01103",
  },
  LU: {
    address1: "12 Avenue de la Liberté",
    address2: "",
    city: "Luxembourg City",
    company: "Luxembourg SARL",
    country: "Luxembourg",
    country_code: "LU",
    email: "luxembourg.user@example.com",
    first_name: "Michel",
    last_name: "Schmit",
    phone: "35222123456",
    phone_code: "352",
    province: "",
    province_code: "",
    zip: "L-1930",
  },
  MT: {
    address1: "Triq ir-Repubblika",
    address2: "",
    city: "Valletta",
    company: "Malta Ltd.",
    country: "Malta",
    country_code: "MT",
    email: "maltese.user@example.com",
    first_name: "Joseph",
    last_name: "Calleja",
    phone: "35621234567",
    phone_code: "356",
    province: "",
    province_code: "",
    zip: "VLT 1111",
  },
  PT: {
    address1: "Rua Augusta 100",
    address2: "",
    city: "Lisbon",
    company: "Portugal SA",
    country: "Portugal",
    country_code: "PT",
    email: "portuguese.user@example.com",
    first_name: "Manuel",
    last_name: "Silva",
    phone: "351212345678",
    phone_code: "351",
    province: "",
    province_code: "",
    zip: "1100-048",
  },
  SK: {
    address1: "Štúrova 3",
    address2: "",
    city: "Bratislava",
    company: "Slovakia s.r.o.",
    country: "Slovakia",
    country_code: "SK",
    email: "slovak.user@example.com",
    first_name: "Peter",
    last_name: "Novak",
    phone: "421212345678",
    phone_code: "421",
    province: "",
    province_code: "",
    zip: "811 02",
  },
  SI: {
    address1: "Prešernova cesta 8",
    address2: "",
    city: "Ljubljana",
    company: "Slovenia d.o.o.",
    country: "Slovenia",
    country_code: "SI",
    email: "slovenian.user@example.com",
    first_name: "Matej",
    last_name: "Kranjc",
    phone: "38631234567",
    phone_code: "386",
    province: "",
    province_code: "",
    zip: "1000",
  },
  ES: {
    address1: "Calle Gran Vía 20",
    address2: "",
    city: "Madrid",
    company: "España SA",
    country: "Spain",
    country_code: "ES",
    email: "spanish.user@example.com",
    first_name: "Carlos",
    last_name: "García",
    phone: "34912345678",
    phone_code: "34",
    province: "",
    province_code: "",
    zip: "28013",
  },
  CZ: {
    address1: "Václavské náměstí 1",
    address2: "",
    city: "Prague",
    company: "Czechia s.r.o.",
    country: "Czech Republic",
    country_code: "CZ",
    email: "czech.user@example.com",
    first_name: "Petr",
    last_name: "Novák",
    phone: "420212345678",
    phone_code: "420",
    province: "",
    province_code: "",
    zip: "110 00",
  },
  DK: {
    address1: "Østergade 36",
    address2: "",
    city: "Copenhagen",
    company: "Denmark ApS",
    country: "Denmark",
    country_code: "DK",
    email: "danish.user@example.com",
    first_name: "Lars",
    last_name: "Jensen",
    phone: "4532123456",
    phone_code: "45",
    province: "",
    province_code: "",
    zip: "1100",
  },
  HU: {
    address1: "Andrássy út 10",
    address2: "",
    city: "Budapest",
    company: "Hungary Kft.",
    country: "Hungary",
    country_code: "HU",
    email: "hungarian.user@example.com",
    first_name: "István",
    last_name: "Kovács",
    phone: "3612345678",
    phone_code: "36",
    province: "",
    province_code: "",
    zip: "1061",
  },
  PL: {
    address1: "ul. Marszałkowska 99",
    address2: "",
    city: "Warsaw",
    company: "Poland Sp. z o.o.",
    country: "Poland",
    country_code: "PL",
    email: "polish.user@example.com",
    first_name: "Jan",
    last_name: "Kowalski",
    phone: "48221234567",
    phone_code: "48",
    province: "",
    province_code: "",
    zip: "00-120",
  },
  RO: {
    address1: "Strada Victoriei 15",
    address2: "",
    city: "Bucharest",
    company: "Romania SRL",
    country: "Romania",
    country_code: "RO",
    email: "romanian.user@example.com",
    first_name: "Ion",
    last_name: "Popescu",
    phone: "40212345678",
    phone_code: "40",
    province: "",
    province_code: "",
    zip: "010082",
  },
  SE: {
    address1: "Drottninggatan 10",
    address2: "",
    city: "Stockholm",
    company: "Sweden AB",
    country: "Sweden",
    country_code: "SE",
    email: "swedish.user@example.com",
    first_name: "Erik",
    last_name: "Svensson",
    phone: "4681234567",
    phone_code: "46",
    province: "",
    province_code: "",
    zip: "111 51",
  },
};
